name: 'Lighthouse User Flow CI Action'
description: "Audit URL's using Lighthouse user flow and test performance within PR's. Optionally show reports as a comment"
inputs:
  # GLOBAL ============================================
  rcPath:
    description: 'Path to a UFCI user-flowrc.json file'
    required: false
    default: '.user-flowrc.json'
  verbose:
    description: 'Verbose logging flag ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
  dryRun:
    description: 'Faster runs due to dummy results for reports ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
outputs:
  resultPath: # path to md output
    description: 'The path in with the user flow results are saved'
  resultSummary: # md report as string of all user flows
    description: 'The summary report of all user flow results of the current run'
runs:
  using: "composite"
  steps:
    - name: "Run user-flow"
      id: ruf
      uses: ./packages/user-flow-gh-action/src/app/
      with:
        dryRun: ${{ inputs.dryRun }}
        verbose: ${{ inputs.verbose }}
        rcPath: ${{ inputs.rcPath }}
    - name: Add reduced report as comment to the PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: user flow summary report
        message: ${{ steps.ruf.outputs.resultSummary }}

branding:
  icon: 'bar-chart-2' # un-sorted bar chart
  color: 'gray-dark'
