name: 'Lighthouse User Flow CI Action'
description: "Audit URL's using Lighthouse user flow and test performance within PR's"
inputs:
  # GLOBAL ============================================
  rcPath:
    description: 'Path to a UFCI user-flowrc.json file'
    required: false
    default: '.user-flowrc.json'
  verbose:
    description: 'Verbose logging flag ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
  dryRun:
    description: 'Faster runs due to dummy results for reports ("on" or "off")'
    required: false
    # has to be in line with @push-based/user-flow/packages/cli/src/lib/pre-set.ts#CI_PRESET
    default: 'off'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install the dependencies
      shell: bash
      run: npm ci
      env:
        INPUT_NAME: ${{ inputs.name }}
    - name: run:user-flow
      id: ruf2
      shell: bash
      run: node ${{ github.action_path }}/dist/packages/user-flow-gh-action/main.js
    #- name: "Run user-flow"
    #  id: ruf
    #  uses:  ${{ github.action_path }}/dist/packages/user-flow-gh-action
    #  with:
    #    dryRun: ${{ inputs.dryRun }}
    #    verbose: ${{ inputs.verbose }}
    #    rcPath: ${{ inputs.rcPath }}
    # Reads to user flow report form the step output and adds a comment to the PR
    - name: Add reduced report as comment to the PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: user flow summary report
        message: ${{ steps.ruf.outputs.resultSummary }}
branding:
  icon: 'bar-chart-2' # un-sorted bar chart
  color: 'gray-dark'
