name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install
        run: npm i
      - name: build:action
        run: nx build action
      - name: commit:build:action (GitHub's registry is GitHub so we need it compiled)
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Persist action build'
          add: '*'
      - name: test:action
        run: nx test action
      - name: Run test action locally
        id: localRun
        uses: ./
        with:
          dryRun: 'off'
          verbose: 'on'
          rcPath: ./.user-flowrc.json
