name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install
        run: npm i
      - name: build
        run: npm run nx -- affected:build --base=remotes/origin/master
      - name: Commit build
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Persist build'
          add: '*'
      - name: test
        run: npm run nx -- affected:test --base=remotes/origin/master
      - name: Run build user-flow-gh-action
        uses: ./dist/packages/user-flow-gh-action
        with:
          milliseconds: '2000'
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          milliseconds: 1000
