name: 'Build and test user-flow action'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install
        run: npm i
      - name: build:user-flow-gh-action
        run: nx build user-flow-gh-action
      - name: commit:build:user-flow-gh-action (GitHub's registry is GitHub so we need it compiled)
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Persist user-flow-gh-action'
          add: '*'
      - name: test:user-flow-gh-action
        run: nx test user-flow-gh-action
      - name: e2e:user-flow-gh-action
        run: nx test user-flow-gh-action-e2e
      - name: Run test user-flow-gh-action locally
        id: localRun
        uses: ./dist/packages/user-flow-gh-action/
        with:
          dryRun: 'off'
          verbose: 'on'
          rcPath: ./.user-flowrc.json
          serverBaseUrl: push-based.io
          serverToken: 123
      - name: local-test
        run: npm run postLocalCiRunTest -- --rp=${{ steps.localRun.outputs.resultPath }} --r="${{ steps.localRun.outputs.resultSummary }}"
